run_tests:
  image: php:8.2.3
  before_script:
    - echo nameserver 8.8.8.8 > /etc/resolv.conf
    - apt-get update -yqq
    - apt-get install -yqq git iputils-ping libzip-dev zip
    - docker-php-ext-install zip mysqli pdo_mysql
    - php -r "readfile('https://getcomposer.org/installer');" > composer-setup.php
    - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
    - php -r "unlink('composer-setup.php');"
    - chmod +x /usr/local/bin/composer
    - composer install --ignore-platform-reqs --no-scripts
  services:
    - name: mariadb:10.9.3
      alias: db
  variables:
    MYSQL_ROOT_PASSWORD: 'codechallenge'
    MYSQL_USER: 'codechallenge'
    MYSQL_PASSWORD: 'codechallenge'
  script:
      - php bin/console --env=test doctrine:database:create --if-not-exists --no-interaction
      - bin/console --env=test doctrine:schema:create --no-interaction
      - php bin/phpunit --testdox
