variables:
  IMAGE_NAME: javierdelavega/codechallenge
  IMAGE_TAG: latest

stages:
  - test
  - build

run_tests:
  stage: test
  image: php:8.2.3
  before_script:
    - bash ci/docker_install.sh > /dev/null
  services:
    - name: mariadb:10.9.3
      alias: db
  variables:
    MYSQL_ROOT_PASSWORD: 'codechallenge'
    MYSQL_USER: 'codechallenge'
    MYSQL_PASSWORD: 'codechallenge'
  script:
      - php bin/console --env=test doctrine:database:create --if-not-exists --no-interaction
      - bin/console --env=test doctrine:schema:create --no-interaction
      - php bin/phpunit --testdox
build_image:
  stage: build
  image: docker:24.0.6
  services:
    - docker:24.0.6-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG -f ci/Dockerfile --target prod .
    - docker push $IMAGE_NAME:$IMAGE_TAG