run_tests:
  image: php:8.2.3
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq git iputils-ping
    - ping -c 6 google.com
    - ping -c 6 getcomposer.org
    - php -r "readfile('https://getcomposer.org/installer');" > composer-setup.php
    - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
    - php -r "unlink('composer-setup.php');"
    - chmod +x /usr/local/bin/composer
    - composer install --ignore-platform-reqs --no-scripts
  script:
      - php bin/phpunit --testdox --testsuite Entities,ValueObjects,DTOs,Events,Utils
