run_tests:
  image: php:8.2.3
  before_script:
    - bash ci/docker_install.sh > /dev/null
  services:
    - name: mariadb:10.9.3
      alias: db
  variables:
    MYSQL_ROOT_PASSWORD: 'codechallenge'
    MYSQL_USER: 'codechallenge'
    MYSQL_PASSWORD: 'codechallenge'
  script:
      - php bin/console --env=test doctrine:database:create --if-not-exists --no-interaction
      - bin/console --env=test doctrine:schema:create --no-interaction
      - php bin/phpunit --testdox
